use express_test;

CREATE TABLE FITNESS_PRICES_TABLE (
    id INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    month INT(2) NOT NULL,
    price INT(8) NOT NULL,
    `order` INT(2) NOT NULL
);

ALTER TABLE FITNESS_PRICES_TABLE ADD COLUMN fitness_center_id INT(5) NOT NULL;

ALTER TABLE FITNESS_PRICES_TABLE ADD CONSTRAINT fk_fitness_center FOREIGN KEY (fitness_center_id) REFERENCES FITNESS_CENTERS(id);