CREATE TABLE POSTS (
  id INT(5) AUTO_INCREMENT PRIMARY KEY,
  author_id(30) INT NOT NULL,
  title VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  like_count INT(2) DEFAULT 0,
  dislike_count INT(2) DEFAULT 0,
  view_count INT(5) DEFAULT 0,
  category ENUM('INFORMATION', 'AMITY', 'CERTIFICATIONS', 'FAQ') NOT NULL DEFAULT 'INFORMATION',
  lat DECIMAL(10, 6) NOT NULL,
  lng DECIMAL(11, 7) NOT NULL,
  is_liked BOOLEAN DEFAULT FALSE,
  is_disliked BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES USERS(id)
);
