CREATE TABLE POSTS_IMAGES (
  id INT(5) AUTO_INCREMENT PRIMARY KEY,
  post_id INT(5) NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  `order` INT(1) NOT NULL,
  FOREIGN KEY (post_id) REFERENCES POSTS(id)
);
