CREATE TABLE REACTIONS (
  id INT(5) AUTO_INCREMENT PRIMARY KEY,
  post_id INT(5) NOT NULL,
  user_id INT(5) NOT NULL,
  reaction_type ENUM('LIKE', 'DISLIKE') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES POSTS(id),
  FOREIGN KEY (user_id) REFERENCES USERS(id)
);